// Generated by https://quicktype.io
import { Rights } from './role.model';

export interface LoginResponse {
  expiresAt: string;
  token: string;
  userData: UserData;
}

export interface UserData {
  _id: string;
  firstName: string;
  email: string;
  createdAt: string;
  updatedAt: string;
  roleSummary: RoleSummary;
  admin: boolean;
}

export interface RoleSummary {
  specialRights: any[];
  roleNames: string[];
  moduleRights: { [moduleName: string]: Rights };
}
