// Generated by https://quicktype.io

export interface Role {
  _id?: string;
  specialRights: string[];
  name: string;
  moduleRights: ModuleRight[];
  createdAt?: string;
  updatedAt?: string;
}

export interface ModuleRight {
  rights: Rights;
  _id: string;
  module: string;
}

export interface Rights {
  read: boolean;
  create: boolean;
  update: boolean;
  delete: boolean;
}
